<template>
    <div>
         <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    </div>
</template>
<script lang="ts">
export default {
    
}
</script>
<style lang="scss">
    
</style>